/*
using System;

class Pre_PostDemo
{
    static void Main()
    {
        int x, y;
        int i;

        Console.WriteLine("Series Generated by using y = y + x++;");
        x = 1;
        y = 0;

        for (i = 0; i < 10; i++)
        {
            y = y + x++;  // Postfix ++
            Console.WriteLine(y + " ");
        }

        Console.WriteLine();

        Console.WriteLine("Series Generated by using y = y + ++x;");
        x = 1;
        y = 0;

        for (i = 0; i < 10; i++)
        {
            y = y + ++x;
            Console.WriteLine(y + " ");
        }
    }
}
*/